### PR TITLE
FY23_Q2_GithubIssuesRound3_john

### PR DESCRIPTION
**Pull request by johnpierson**
This includes fixes for screenshots, DYNs migrated to 2.13 and other cleanup.

### CODE REVIEW

**Comment by lillismith** [comment]
@johnpierson  this PR seems to have a lot of stuff in it from 2 years ago (!)  Did I neglect to accept this then - yikes!?  Are these still valid?

**Comment by johnpierson** [comment]
Oh yeah. This one should have went through.

**Comment by lillismith** [comment]
Do you mean I should have merged it a long time ago?

**Comment by lillismith** [comment]
OOps, ok, well OK to merge it all now?

**Comment by johnpierson** [comment]
Yes, and they should still merge just fine now. :) (However this did not fix the issue the user was having on the forum)

**Pull request merged**
