### PR TITLE
Create 99-04_HiringProfessionalHelp

### PR DESCRIPTION
**Pull request by lillismith**
Hi, could you add this Job Description to the index?  I wasn't sure how to make it markdown....

### CODE REVIEW

**Comment by SHKnudsen** [comment]
@lillismith can you check that this is how it should look?
https://github.com/DynamoDS/RefineryPrimer/blob/lilli-computationaldesignerjobdescription/99-appendix/99-04_computational-design-job-description.md

**Comment by lillismith** [comment]
Any formatting improvements welcome.  Also if you can embed that link, that would be great.

**Comment by lillismith** [comment]
one more change, can we call it "Hiring Professional Help"

**Comment by SHKnudsen** [comment]
okay, take a look now

**Comment by lillismith** [comment]
Sorry, I meant the file title.  Will show you what I mean.

**Comment by lillismith** [comment]
Ugh, sorry I'm a dork! I get it now https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet.  None of this is urgent at all. Thanks for helping me learn!

**Comment by lillismith** [comment]
OK to merge this in?

**Comment by SHKnudsen** [comment]
@lillismith yes, should be ok to merge in.

**Pull request merged**
